# Generated by Django 3.0 on 2020-12-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todorestapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmapping',
            name='studentid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studentid', to='todorestapi.Users'),
        ),
        migrations.AlterField(
            model_name='taskmapping',
            name='taskid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taskid', to='todorestapi.Tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to='todorestapi.Users'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='todorestapi.TaskStatus'),
        ),
    ]
