# Generated by Django 3.0 on 2020-12-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todorestapi', '0002_auto_20201225_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='taskmapping',
            name='taskid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasksid', to='todorestapi.Tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
