# Generated by Django 3.0 on 2020-12-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todorestapi', '0003_auto_20201226_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmapping',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='taskmapping',
            name='taskid',
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='todorestapi.Users'),
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todorestapi.Tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='todorestapi.Users'),
        ),
    ]
