# Generated by Django 3.0 on 2020-12-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todorestapi', '0004_auto_20201226_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='todorestapi.Users'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='todorestapi.TaskStatus'),
        ),
    ]
