# Generated by Django 3.0 on 2020-12-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todorestapi', '0005_auto_20201226_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
